index:
    pattern: /
    defaults: {_controller: 'AppBundle:Index:index' }

bookshop_latest:
    pattern: /books/latest
    defaults: { _controller : 'AppBundle:Bookshop:latest' }

bookshop_oldest:
    pattern: /books/oldest
    defaults: { _controller : 'AppBundle:Bookshop:oldest' }

bookshop_create_random:
    pattern: /books/createRandom
    defaults: { _controller : 'AppBundle:Bookshop:createRandom' }
