AppBundle\Entity\Author:
    type: entity
    table: author
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        forename:
            type: string
            length: 255
        surname:
            type: string
            length: 255
    lifecycleCallbacks: {  }
